apiVersion: v1
kind: ReplicationController
metadata:
  name: rc1
spec:
  replicas: 5
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: httpd
          ports:
            - containerPort: 80
